version: '3.8'

services:
  check-qb:
    image: unraiders/check-qb:1.0.0
    container_name: check-qb
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
